default: zhipu
clients:
  openai:
    type: openai
    model: "text-embedding-ada-002"
    api_key: "${OPENAI_API_KEY}"
    batch_size: 20
  zhipu:
    type: zhipu
    model: "embedding-2"
    api_key: "a2dad7daa69c48418d0dd0b3df939783.WJaSrMGkYP7zUPLx"
    timeout: 5.0
  hf:
    type: hf
    model_name: "/Users/caixiaomeng/models/hf/bge-large-zh-v1.5"