# ES索引流水线配置
components:
  # 文档加载器
  document_loader:
    type: "loader"
    name: "file"
    config:
      path: "./test_cases/test_data"
      file_types: [".txt", ".md"]
      encoding: "utf-8"
      debug: true
  
  # 文档分割器
  text_splitter:
    type: "splitter"
    name: "hierarchical"
    config:
      chunk_sizes: [512, 256]
      chunk_overlap: 50
      include_metadata: true
      include_prev_next_rel: true
      debug: true
  
  # ES索引器
  es_indexer:
    type: "indexer"
    name: "elasticsearch"
    config:
      index_name: "performance_docs"
      host: "localhost"
      port: 9200
      username: "elastic"
      password: "sPxLec=NGSFmUT_7+74R"
      use_ssl: true
      verify_certs: false
      batch_size: 50
      mapping:
        properties:
          content:
            type: "text"
            analyzer: "standard"
          title:
            type: "text"
            analyzer: "standard"
          metadata:
            type: "object"
          timestamp:
            type: "date"
      settings:
        number_of_shards: 1
        number_of_replicas: 0
        analysis:
          analyzer:
            default:
              type: "standard"
      debug: true

# 流程定义 - 索引流程
flow:
  # 索引流程：文档加载 -> 分割 -> 索引
  document_loader: ["text_splitter"]
  text_splitter: ["es_indexer"]
  es_indexer: []  # 索引完成后结束

# 入口点
entry_point: "document_loader"