debug: true  # 启用debug日志
entry_point: "loader"  # 入口组件

components:
  loader:
    type: "loader.file"  # 组件类型，格式为 "<组件类型>.<组件名>"
    path: "/Users/caixiaomeng/Projects/Python/PerformanceRag/test_cases/test_data/"
    file_types: [".txt", ".md"]

flow:
  loader: []  # 没有下一个组件