generation_pipeline:
  components:
    document_loader:
      type: loader
      name: file
      config:
        path: "./test_cases/test_data"
        file_types: [".txt", ".md"]
        debug: true

    text_splitter:
      type: splitter
      name: recursive
      config:
        chunk_size: 500
        chunk_overlap: 50
        debug: true

    bm25_indexer:
      type: indexer
      name: bm25
      config:
        index_name: "generation_test"
        storage_path: "./data/bm25_index"
        auto_save: true
        debug: true

    bm25_retriever:
      type: retriever
      name: bm25
      config:
        index_name: "generation_test"
        storage_path: "./data/bm25_index"
        top_k: 5
        auto_load: true
        debug: true

    llm_generator:
      type: generator
      name: llm
      config:
        prompt_template: "retrieval_prompt"
        system_prompt: "你是一个专业的技术文档助手，请根据提供的文档内容准确回答用户问题。"
        debug: true

    template_generator:
      type: generator
      name: template
      config:
        template_name: "retrieval_prompt"
        max_context_length: 2000
        debug: true

  flow:
    index_flow:
      - document_loader
      - text_splitter
      - bm25_indexer
    
    query_flow:
      - bm25_retriever
      - llm_generator

  entry_points:
    index: "document_loader"
    query: "bm25_retriever"