debug: true  # 启用debug日志
entry_point: "loader"  # 入口组件

components:
  loader:
    type: "loader.file"
    path: "/Users/caixiaomeng/Projects/Python/PerformanceRag/test_cases/test_data/recursive_splitter_data.md"
    file_types: [".txt", ".md"]
    next: "splitter"
    
  splitter:
    type: "splitter.hierarchical_doc"
    chunk_sizes: [512, 256]
    chunk_overlap: 20
    include_metadata: true
    max_chunk_size: 1024
    
    # 新增fallback配置
    fallback_config:
      # 第一级退化：语义分割器
      primary:
        type: "semantic"
        chunk_size: 1024
        chunk_overlap: 20
        similarity_threshold: 0.8
        min_chunk_size: 100
        embedding_model: "embedding-3"
        embedding_api_key: "9dec52aca0e144fc98f3ab8d407e9a57.MNrL3f2b8cgfRsHh" 
        embedding_api_base: "https://open.bigmodel.cn/api/paas/v4" 
        max_chunk_size: 1024
        include_metadata: true
        batch_size: 4
        
      # 第二级退化：文本分割器（最终兜底）
      secondary:
        type: "text"
        chunk_size: 1024
        chunk_overlap: 20
        split_method: "character"
        include_metadata: true

flow:
  loader: ["splitter"]
  splitter: []