# 索引配置
# 支持多种索引类型，默认embedding

default: embedding
clients:
  embedding:
    type: embedding
    persist_dir: ./data/index/embedding
    max_worker: 8
    # 可扩展更多参数
  bm25:
    type: bm25
    persist_dir: ./data/index/bm25
    max_worker: 8
    # 可扩展更多参数
  # tree:
  #   type: tree
  #   persist_dir: ./data/index/tree 