default: "openai"  # 默认使用的LLM客户端

clients:
  openai:
    type: "openai"
    model: "qwen-plus"
    api_key: "sk-2e6fe63e9e844676bceabc6f91a948be"  # 或通过环境变量OPENAI_API_KEY设置
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    max_tokens: 8192
    timeout: 60

  zhipu:
    type: "zhipu"
    model: "glm-4-flash-250414"
    api_key: "2de2c50a16b2abd14ead1d39ee20ccd4.ttmQMnxQyQN5rmeN"  # 或通过环境变量设置
    base_url: "https://open.bigmodel.cn/api/paas/v4"
    temperature: 0.7
    max_tokens: 8192
    timeout: 60
