default: "zhipu"  # 默认使用的LLM客户端

clients:
  openai:
    type: "openai"
    model: "gpt-3.5-turbo"
    api_key: "your-openai-api-key"  # 或通过环境变量OPENAI_API_KEY设置
    base_url: "https://api.openai.com/v1"
    temperature: 0.7
    max_tokens: 4096
    timeout: 60

  zhipu:
    type: "zhipu"
    model: "glm-4-flash-250414"
    api_key: "2de2c50a16b2abd14ead1d39ee20ccd4.ttmQMnxQyQN5rmeN"  # 或通过环境变量设置
    base_url: "https://open.bigmodel.cn/api/paas/v4"
    temperature: 0.7
    max_tokens: 8192
    timeout: 60
