# 生产者-消费者Pipeline配置
architecture:
  type: "producer_consumer"
  
# 生产者部分（数据预处理，包括embedding）
producer:
  components:
    document_loader:
      type: "loader"
      name: "file"
      config:
        path: "/Users/caixiaomeng/Projects/Python/EasyRAG/data/format_data_with_img"
        file_types: [".txt", ".md"]
        encoding: "utf-8"
        debug: true
    
    text_splitter:
      type: "splitter"
      name: "hierarchical"
      config:
        chunk_sizes: [512, 256]
        chunk_overlap: 50
        include_metadata: true
        max_chunk_size: 600
        fallback_config:
          primary:
            type: "text"
            split_method: "character"
            chunk_size: 400
            chunk_overlap: 50
            include_metadata: true
        debug: true
    
    # 将embedding移到生产者部分
    openai_embedding:
      type: "embedding"
      name: "openai"
      config:
        model: "models/bge-m3"
        api_key: "123456"
        api_base: "http://workspace.featurize.cn:33336/v1"
        batch_size: 100  # 缓存大小，凑齐100条再请求
        timeout: 60
        max_retries: 3
        debug: true
  
  # 生产者流程：文档加载 -> 文本分割 -> embedding -> 输出到队列
  flow:
    document_loader: ["text_splitter"]
    text_splitter: ["openai_embedding"]
    openai_embedding: []  # 输出到队列
  
  entry_point: "document_loader"

# 消费者部分（只负责快速ES写入）
consumer:
  components:
    es_vector_indexer:
      type: "indexer"
      name: "elasticsearch"
      config:
        index_name: "vector_performance_docs"
        host: "localhost"
        port: 9200
        username: "elastic"
        password: "sPxLec=NGSFmUT_7+74R"
        use_ssl: true
        verify_certs: false
        batch_size: 100  # 减少batch_size，避免超时
        timeout: 30
        debug: true
        # 优化ES索引设置
        index_settings:
          number_of_shards: 1
          number_of_replicas: 0  # 禁用副本提高写入速度
          refresh_interval: "30s"  # 延长刷新间隔
          translog:
            durability: "async"  # 异步事务日志
        mapping:
          properties:
            content:
              type: "text"
              analyzer: "standard"
            content_vector:
              type: "dense_vector"
              dims: 1024  # 需要改为 BGE-M3 的实际维度
              index: true
              similarity: "cosine"
            metadata:
              type: "object"
            timestamp:
              type: "date"
  
  # 消费者流程：只负责ES索引
  flow:
    es_vector_indexer: []
  
  entry_point: "es_vector_indexer"
  
  # 消费者配置
  config:
    batch_size: 50        # 增加批次大小
    max_queue_size: 1000  # 减少队列大小
    producer_tasks: 1   # 增加生产者线程
    consumer_tasks: 3   # 减少消费者线程
    timeout: 30
    rate_limit_per_second: 10  # 提高速率限制