default: rewrite
modules:
  rewrite:
    type: rewrite
    # 可扩展llm_config
  hyde:
    type: hyde
    # 可扩展llm_config
  multi_query:
    type: multi_query
    n: 3
    # 可扩展llm_config
  decompose:
    type: decompose
    # 可扩展llm_config
  disambiguate:
    type: disambiguate
    # 可扩展llm_config
  abstract:
    type: abstract
    # 可扩展llm_config 