# ES检索器配置
es_retriever:
  type: "elasticsearch"
  name: "es_retriever"
  host: "localhost"
  port: 9200
  username: "elastic"
  password: "your_password"
  use_ssl: true
  verify_certs: false
  index_name: "performance-rag-index"
  search_type: "hybrid"  # text, vector, hybrid
  top_k: 10
  similarity_threshold: 0.1
  embedding:
    type: "hf"  # hf, openai, bge_embedding
  debug: true

# BM25检索器配置
bm25_retriever:
  type: "bm25"
  name: "bm25_retriever"
  index_name: "test_documents"
  k1: 1.5
  b: 0.75
  top_k: 10
  similarity_threshold: 0.0
  storage_path: "./data/bm25_index"
  auto_load: true
  debug: true

# 检索器流水线配置
retriever_pipeline:
  retrievers:
    - type: "elasticsearch"
      name: "es_retriever"
      host: "localhost"
      port: 9200
      search_type: "vector"
      top_k: 5
      embedding:
        type: "hf"
    - type: "bm25"
      name: "bm25_retriever"
      k1: 1.5
      b: 0.75
      top_k: 5