# 文本分割器配置
text:
  type: text
  chunk_size: 1000
  chunk_overlap: 200
  split_method: char  # char, word, sentence
  separator: "\n"
  keep_separator: true

# 递归分割器配置
recursive:
  type: recursive
  chunk_size: 1000
  chunk_overlap: 200
  separators: ["\n\n", "\n", "。", "！", "？", "；", "，", " ", ""]
  keep_separator: true

# 语义分割器配置
semantic:
  type: semantic
  chunk_size: 1000
  chunk_overlap: 200
  similarity_threshold: 0.8
  min_chunk_size: 100 

# 层次化分割器配置
hierarchical:
  type: hierarchical_node 
  type: hierarchical
  chunk_sizes: [512, 256]
  chunk_overlap: 20
  include_metadata: true
  include_prev_next_rel: true 